package edu.chl.mailbowser.event;

/**
 * Created by mats on 29/04/15.
 *
 * An enum for all possible event types.
 */
public enum EventType {
    ADD_ACCOUNT,
    REMOVE_ACCOUNT,
    SELECT_EMAIL,
    ADD_TAG_TO_EMAIL,
    REMOVE_TAG_FROM_EMAIL,
    FETCHED_EMAIL,
    FETCHED_ALL_EMAILS,
    FETCHED_ALL_EMAILS_FAILED,
    SEND_EMAIL,
    SEND_EMAIL_FAIL,
    SELECT_TAG,
    CLEAR_EMAILS,
    SEARCH,
    DELETE_TAG,
    DELETE_EMAIL,
    OPEN_COMPOSE_EMAIL_WINDOW,
    OPEN_COMPOSE_EMAIL_WINDOW_FORWARD,
    OPEN_COMPOSE_EMAIL_WINDOW_REPLY,
    OPEN_COMPOSE_EMAIL_WINDOW_REPLY_ALL,
    ADDED_TAG_TO_EMAIL,
    DELETED_TAG,
    REMOVED_TAG_FROM_EMAIL, OPEN_ADD_TAG_WINDOW, FXML_LOADED
}
